{% set version = "0.9-11" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fftwtools
  version: {{ version|replace("-", "_") }}

source:
  fn: fftwtools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/fftwtools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/fftwtools/fftwtools_{{ version }}.tar.gz
  sha256: f1f0c9a9086c7b2f72c5fb0334717cc917213a004eaef8448eab4940c9852c7f

build:
  merge_build_host: true  # [win]
  number: 0
  # unsatisfiable dependencies ?
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - fftw 3.3.8

  run:
    - r-base
    - fftw 3.3.8

test:
  commands:
    - $R -e "library('fftwtools')"  # [not win]
    - "\"%R%\" -e \"library('fftwtools')\""  # [win]

about:
  home: https://github.com/krahim/fftwtools
  license: GPL-2.0-or-later
  summary: "Provides a wrapper for several 'FFTW' functions. This package provides access to the two-dimensional 'FFT', the multivariate 'FFT', and the one-dimensional real to complex 'FFT' using the 'FFTW3' library. The package includes the functions fftw() and mvfftw() which are designed to mimic the functionality of the\
    \ R functions fft() and mvfft(). The 'FFT' functions have a parameter that allows them to not return the redundant complex conjugate when the input is real data. "

  license_family: GPL3

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
