travis:
  secure:
    BINSTAR_TOKEN: Ci7GI3tCx0x6GPUrccfQ3z4Ecaoo+T2O0pBMhIjMh710dIZCwUTAVUs1nf3EOlDtyrmiNfbfNv+120MFGabpEgw0rHz22K6gbUY4AGfTBfsnDuNyhn2VtTqibo8Gj7Yjk8QPKa28AyFRtLl+2f8UMtIf58nM2yNMpf/Ebz3GyjAyFvkVvEHBiaaLiil9njSpI/HbiVDCMkfrb2ppyJ/AJoXcOEAYJ6NApArbL4aBSL8kmNKT4ovXSqNW7JR93Yak1KMk488qRCtkVf/0Ti9OA1vUIy8cczkVRBJL4znF3Ff07Vl2f6W7ma2Th3E6A7QOi3To3KPDMyv0J2PrYWjDKHDQ1LeMMzHISeeCKIAMzej09WbYUUITMOlx0Nl711o3E/WsOEVLNo8HGvmL0uAaA2tH9PUhJd0e3wQ2b4Tzs0DXfCziIokHUqn6kPZ5SAuPxQWOvrYVuhohlrx42UenTwlDYGiIPkVoeUkM21W9RvQVR7p9sRvy4DjbMt1V7YeRc3h+gx5Znpej0MQMGE99WD6SL+1cO0Xf2KIzQSDNa9NdQlwSx3wWbK1rCox1dMJ+XFXkSouIFk4LGBPqpKauV6/fCgZo6bmjKmXTiKpkEQJ4imp5jgfKmGoW1A8HtDZoZIRhhk87hSvZ5OiqhRdzVXkQ4NYdaQXWUSKnBHZpLgM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
