travis:
  secure:
    BINSTAR_TOKEN: DIywQpwhWTjiwSMHzyq9ZRJWwO7Hj9/vwAhQrXAjpRUL5k0HPuFNAnwVr4C5hr2iO8wptmSkC/2EyNS3I/d5aSRE7uKqHwY41aPW8ahCYrIa9wSahh6hw1mfuZpE9Mto0vewTswfmqbI+HiOmGBGC8WFCD4zxTWwG4OpjGxMVC5nIa3Ml8y5CN/qN6mqg8Vk7cNWL/FCy9srj0zXqihpXBoDXQvkmOptES20PnI8ZcCr6gOawyep02twGT9PJMWwyye+1uUR+OyYLxE5HWw5n0HVAqBoV4t/qy07NLerRj7u6XlUYik/Ebokbd7a+qbVw379JZsxHsp4JcZLWQnLbvT6C8uxM9YfX5CSKPRQpA1U7umQY+RTYApweZw2veeN6PTanQViq6e3pkB7qQxe90sR3G80l+FNfA1dJ2xiSnXx+98YrYaLnGgbVqukhxhJs4JCxLBUhv7q5k8Pu5t1K8QxR8jgZwW3EzsgAeOuxpTEdjHdoFWWrFR7cdJhUsDG8Z2fzq2pYaROEKvmCV+FhFjWk77n/88dbC6/+oY3bwfDoFdUMzzY68U6IEA94HD39UV7cA8nlvd5D48Z494ub2SXeOSSFdH1WpPMi4h+hSqW8CPrkB0u0FRWm7PfEJW1FZb+OGwQMPs8ma98M2uDMR2TKegEMN0CJ3eEHEfVlmc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
